import type { DashboardPayload } from "@/lib/types";

export const fallbackDashboard: DashboardPayload = {
  synced_at: new Date("2026-06-05T09:00:00.000Z").toISOString(),
  source_count: 4,
  systems: [
    {
      id: "digital-audit",
      code: "SYS-AUDIT",
      name: "디지털감사시스템",
      category: "감사/통제",
      description: "감사 운영 현황과 연관 시스템 영향을 관리하는 통제 중심 시스템입니다.",
      owner_org: "FSO QLT LI2",
      status: "운영중",
      criticality: "상",
      document_name: "HICT_FSO_QLT_LI2_디지털감사시스템_운영매뉴얼(Rev2).docx",
      document_path: "docs/HICT_FSO_QLT_LI2_디지털감사시스템_운영매뉴얼(Rev2).docx",
      revision: "Rev2",
      excerpt: "감사 계획, 결과, 후속조치까지 관리하는 운영매뉴얼 기반 시스템 정보입니다.",
      functions: [
        { name: "감사 계획 관리", description: "감사 일정과 대상을 등록합니다." },
        { name: "조치 이력 추적", description: "감사 결과와 후속조치를 추적합니다." },
      ],
      stakeholders: [
        { role: "운영", name: "감사 운영 담당", department: "감사기획팀", contact: "내부 문의" },
        { role: "개발", name: "감사 개발 담당", department: "플랫폼개발팀", contact: "내부 문의" },
      ],
      infra_components: [
        { name: "사용자 채널", type: "Client", specification: "사내 업무 브라우저", environment: "공통" },
        { name: "감사 Web", type: "Web", specification: "Next.js / Nginx", environment: "운영" },
        { name: "감사 API", type: "WAS", specification: "FastAPI", environment: "운영" },
        { name: "감사 DB", type: "DB", specification: "Oracle 19c", environment: "운영" },
      ],
      interfaces: [
        {
          target_system_id: "legal-management",
          target_system_name: "법무관리시스템",
          protocol: "REST",
          direction: "outbound",
          summary: "통제 데이터 공유",
          confidence: "medium",
        },
      ],
      data_assets: [
        { name: "감사 이력", classification: "업무", retention: "3년" },
        { name: "점검 로그", classification: "일반", retention: "1년" },
      ],
      diagram_mermaid: "flowchart LR\n    USER[\"감사 담당자\"] --> WEB[\"감사 Web\"]\n    WEB --> API[\"감사 API\"]\n    API --> DB[(\"감사 DB\")]\n    API --> EXT[\"법무관리시스템\"]",
    },
    {
      id: "legal-management",
      code: "SYS-LEGAL",
      name: "법무관리시스템",
      category: "법무/준법",
      description: "법률 검토, 계약, 준법 지원 정보를 관리하는 시스템입니다.",
      owner_org: "FSO QLT LI2",
      status: "운영중",
      criticality: "상",
      document_name: "HICT_FSO_QLT_LI2_법무관리시스템_운영매뉴얼(Rev1).docx",
      document_path: "docs/HICT_FSO_QLT_LI2_법무관리시스템_운영매뉴얼(Rev1).docx",
      revision: "Rev1",
      excerpt: "법무 업무 프로세스와 내부통제 관점을 함께 다루는 운영매뉴얼 기반 정보입니다.",
      functions: [
        { name: "계약 검토", description: "계약서 검토 요청과 결과를 기록합니다." },
        { name: "준법 관리", description: "준법 이슈와 조치 상태를 관리합니다." },
      ],
      stakeholders: [
        { role: "운영", name: "법무 운영 담당", department: "준법지원팀", contact: "내부 문의" },
      ],
      infra_components: [
        { name: "사용자 채널", type: "Client", specification: "사내 업무 브라우저", environment: "공통" },
        { name: "법무 Web", type: "Web", specification: "Next.js / Nginx", environment: "운영" },
        { name: "법무 API", type: "WAS", specification: "FastAPI", environment: "운영" },
        { name: "법무 DB", type: "DB", specification: "Oracle 19c", environment: "운영" },
      ],
      interfaces: [
        {
          target_system_id: "digital-audit",
          target_system_name: "디지털감사시스템",
          protocol: "REST",
          direction: "inbound",
          summary: "감사/법무 연계",
          confidence: "medium",
        },
        {
          target_system_id: "internal-control",
          target_system_name: "내부통제시스템",
          protocol: "MQ",
          direction: "outbound",
          summary: "통제 이슈 전파",
          confidence: "high",
        },
      ],
      data_assets: [
        { name: "계약 이력", classification: "업무", retention: "5년" },
      ],
      diagram_mermaid: "flowchart LR\n    USER[\"법무 담당자\"] --> WEB[\"법무 Web\"]\n    WEB --> API[\"법무 API\"]\n    API --> DB[(\"법무 DB\")]\n    API --> EXT[\"내부통제시스템\"]",
    },
    {
      id: "internal-control",
      code: "SYS-CTRL",
      name: "내부통제시스템",
      category: "감사/통제",
      description: "통제 항목, 리스크, 개선조치를 관리하는 준법 핵심 시스템입니다.",
      owner_org: "FSO QLT LI2",
      status: "운영중",
      criticality: "상",
      document_name: "org_HICT_FSO_QLT_LI2_내부통제시스템_운영매뉴얼(Rev1).docx",
      document_path: "docs/org_HICT_FSO_QLT_LI2_내부통제시스템_운영매뉴얼(Rev1).docx",
      revision: "Rev1",
      excerpt: "통제 활동과 리스크 관리 프로세스를 지원하는 운영매뉴얼 기반 정보입니다.",
      functions: [
        { name: "통제 점검", description: "통제 활동 점검 현황을 관리합니다." },
        { name: "리스크 추적", description: "리스크와 개선조치를 추적합니다." },
      ],
      stakeholders: [
        { role: "운영", name: "통제 운영 담당", department: "내부통제팀", contact: "내부 문의" },
      ],
      infra_components: [
        { name: "사용자 채널", type: "Client", specification: "사내 업무 브라우저", environment: "공통" },
        { name: "통제 Web", type: "Web", specification: "Next.js / Nginx", environment: "운영" },
        { name: "통제 API", type: "WAS", specification: "FastAPI", environment: "운영" },
        { name: "통제 DB", type: "DB", specification: "PostgreSQL 16", environment: "운영" },
      ],
      interfaces: [
        {
          target_system_id: "legal-management",
          target_system_name: "법무관리시스템",
          protocol: "MQ",
          direction: "inbound",
          summary: "통제 이슈 수신",
          confidence: "high",
        },
      ],
      data_assets: [
        { name: "통제 이력", classification: "업무", retention: "3년" },
      ],
      diagram_mermaid: "flowchart LR\n    USER[\"통제 담당자\"] --> WEB[\"통제 Web\"]\n    WEB --> API[\"통제 API\"]\n    API --> DB[(\"통제 DB\")]",
    },
    {
      id: "nextlab-offering",
      code: "SYS-NEXT",
      name: "NEXTLAB 보유고객향오퍼링시스템",
      category: "영업/오퍼링",
      description: "보유 고객 대상 오퍼링과 캠페인 운영을 관리하는 채널 시스템입니다.",
      owner_org: "FSO QLT LI2",
      status: "운영중",
      criticality: "중",
      document_name: "org_HICT_FSO_QLT_LI2_NEXTLAB 보유고객향오퍼링시스템_운영매뉴얼(Rev1).docx",
      document_path: "docs/org_HICT_FSO_QLT_LI2_NEXTLAB 보유고객향오퍼링시스템_운영매뉴얼(Rev1).docx",
      revision: "Rev1",
      excerpt: "캠페인, 고객 세그먼트, 오퍼링 채널 흐름을 다루는 운영매뉴얼 기반 정보입니다.",
      functions: [
        { name: "캠페인 편성", description: "오퍼링 정책과 대상을 설정합니다." },
        { name: "반응 분석", description: "오퍼링 반응과 실적을 분석합니다." },
      ],
      stakeholders: [
        { role: "운영", name: "오퍼링 운영 담당", department: "디지털마케팅팀", contact: "내부 문의" },
      ],
      infra_components: [
        { name: "사용자 채널", type: "Client", specification: "사내 업무 브라우저", environment: "공통" },
        { name: "오퍼링 Web", type: "Web", specification: "Next.js / Nginx", environment: "운영" },
        { name: "오퍼링 API", type: "WAS", specification: "FastAPI", environment: "운영" },
        { name: "오퍼링 DB", type: "DB", specification: "PostgreSQL 16", environment: "운영" },
      ],
      interfaces: [
        {
          target_system_id: "digital-audit",
          target_system_name: "디지털감사시스템",
          protocol: "Batch",
          direction: "outbound",
          summary: "운영 로그 제공",
          confidence: "low",
        },
      ],
      data_assets: [
        { name: "캠페인 로그", classification: "일반", retention: "1년" },
        { name: "고객 오퍼링 대상", classification: "개인정보", retention: "법정 보관기간 준수" },
      ],
      diagram_mermaid: "flowchart LR\n    USER[\"마케팅 담당자\"] --> WEB[\"오퍼링 Web\"]\n    WEB --> API[\"오퍼링 API\"]\n    API --> DB[(\"오퍼링 DB\")]\n    API --> EXT[\"디지털감사시스템\"]",
    },
  ],
  relations: [
    {
      source_id: "digital-audit",
      target_id: "legal-management",
      label: "업무 연계",
      protocol: "REST",
      confidence: "medium",
    },
    {
      source_id: "legal-management",
      target_id: "internal-control",
      label: "통제 이슈 전파",
      protocol: "MQ",
      confidence: "high",
    },
    {
      source_id: "nextlab-offering",
      target_id: "digital-audit",
      label: "운영 로그 제공",
      protocol: "Batch",
      confidence: "low",
    },
  ],
};
